### ISSUE TITLE
Generator (presenter) to generate and show GS1 on the screen.

### ISSUE THREAD

**Issue by IVANKRUPSKI** [xremix/SwiftGS1Barcode#15]
Hello!

Is it possible to have not only scanner/ parser but also GS1 generator to show it on iPhone's screen? Maybe it's possible to integrate somehow into RSBarcodes_Swift (https://github.com/yeahdongcn/RSBarcodes_Swift)?

And is GS1 the same as GS1 DataBar and GS1 DataBar Expanded?

Thank you!

**Comment by xremix** [comment]
Hello,

this is a great idea in general! As of now this is a library without any UI, and I'd like to keep it like that for now. (Saying this, I want people to use any Scannner Libaray). I think what could be a nice improvement for the app is to extend it so that it also can create a string with the contents of a GS1. Then people could create their own UI, pass the data to this library and show the string in a DataBar / DataMatrix or whatever they would like. What do you think?

Thanks

P.S.: Contributions are always welcome, if you want to contribute could let me know or you can suggest a pull request

**Comment by xremix** [comment]
@IVANKRUPSKI this is mostly build on DataBar Expanded. The main difference is that the variables often have dynamic lengths vs. fixed lengths. I linked the specifications I used in the README.

**Comment by IVANKRUPSKI** [comment]
I wish I could contribute or suggest a pull request but, unfortunately, I am not really a developer
Will try to find someone.

**Comment by xremix** [comment]
@IVANKRUPSKI I'll close this issue for now, as the purpose is to read / identify barcodes contents, but not to generate them.

In the meanwhile, Swift contains some great image filters to generate barcodes:

[https://www.hackingwithswift.com/example-code/media/how-to-create-a-barcode](https://www.hackingwithswift.com/example-code/media/how-to-create-a-barcode)
