### ISSUE TITLE
Fails with the following code:

### ISSUE THREAD

**Issue by soconnor-florio** [xremix/SwiftGS1Barcode#22]
Hello,

Using your parser for a medical app.  We scanned a code and got this output:

"\u{1D}010735003144200717240331103669801C\u{1D}2125816434762607\u{1D}7127098690"

It fails parsing.  I even made a custom instance, stripping away identifiers we don't need:

```
let barcode = GS1Barcode()
        barcode.applicationIdentifiers = [
            "gtin": GS1ApplicationIdentifier("01", length: 14, type: .AlphaNumeric),
            "lotNumber": GS1ApplicationIdentifier("10", length: 20, type: .AlphaNumeric, dynamicLength: true),
            "expirationDate": GS1ApplicationIdentifier(dateIdentifier: "17"),
            "activePotency": GS1ApplicationIdentifier("7004", length: 4, type: .Numeric, dynamicLength: true),
            "serialNumber": GS1ApplicationIdentifier("21", length: 20, type: .AlphaNumeric, dynamicLength: true)
        ]
```

So I'm unclear why it doesn't just ignore the last part:   7127098690

Otherwise we could use the data it's already finding in this code.

**Comment by soconnor-florio** [comment]
The issue is that in this case, when the last chunk of data cannot be matched with any of the supplied application identifiers, the `foundOne` value is false, which will then throw an error.  I'm wondering if it should just be ignored instead of throw an error.  It's a style thing; how strict do you want your library to be?   The workaround not requiring code changes is to catch the didNotFoundApplicationIdentifier and carry on.

**Comment by xremix** [comment]
Hello @soconnor-florio ,
thanks a lot for reaching out on this. I didn't have time to answer as I'm not working this week, but it seems you found the root cause yourself and explained what I was about to answer.
My intention was to have the library a bit more strict, as this was fitting a bit better to my use case, but I decently hear you!
Maybe there could be an parameter that allows to do the check soft vs hard and depending on this crash or not. If this is something you'd like to contribute, feel free! I'd welcome this.

So it seems this works for you now? Are there changes you'd need to make the library work smooth for your use case?

Best regards
